IDENTIFICATION DIVISION.
PROGRAM-ID. HOLA.

DATA DIVISION.
WORKING-STORAGE SECTION.
    01 EDAD         PIC 9(2).
    01 NOMBRE       PIC A(10).
    01 MENSAJE      PIC X(30).
    01 SALARIO      PIC S9(5).
    01 EDAD1        PIC 9(2)       VALUE 18.
    01 NOMBRE       PIC A(10)      VALUE "JUAN".
    01 MENSAJE      PIC X(30)      VALUE "BIENVENIDO".
    01 SALARIO      PIC S9(5)      VALUE 01234.
    01 DECIMILASO   PIC S9(5)V9(2).

PROCEDURE DIVISION.
    ACCEPT EDAD.
    ACCEPT NOMBRE.
    ACCEPT MENSAJE.
    ACCEPT DECIMILASO.