IDENTIFICATION DIVISION.
PROGRAM-ID. 01_HELLO_WORLD.

PROCEDURE DIVISION.
DISPLAY "Enter your name:"
ACCEPT USERNAME
ACCEPT NUMBER
ACCEPT NUMBER2
DISPLAY "Enter your age:"
ACCEPT AGE
DISPLAY "Enter your country:"
ACCEPT COUNTRY
IF AGE = 18
    MOVE "You are a minor." TO MESSAGE
    IF COUNTRY < 14
        DISPLAY "You need parental consent."
    ELSE
        DISPLAY "Consent laws vary by country."
    END-IF
ELSE
    MOVE "You are an adult." TO MESSAGE
END-IF
DISPLAY MESSAGE
ADD 12 TO AGE
ADD COUNTRY TO AGE
SUBTRACT 10 FROM AGE
SUBTRACT USERNAME FROM AGE
DISPLAY AGE
MULTIPLY 12 BY AGE
MULTIPLY COUNTRY BY COUNTRY
DIVIDE 2 INTO AGE
DIVIDE AGE INTO COUNTRY
DIVIDE AGE BY 2
DIVIDE AGE BY COUNTRY

ADD 12 TO 12 GIVING AGE
ADD 12 TO NUMBER GIVING AGE
ADD NUMBER TO 12 GIVING AGE 
ADD NUMBER TO NUMBER2 GIVING AGE

SUBTRACT 5 FROM 10 GIVING RESULT
SUBTRACT NUMBER FROM 20 GIVING TOTAL
SUBTRACT 15 FROM VARIABLE GIVING DIFFERENCE
SUBTRACT NUM1 FROM NUM2 GIVING OUTPUT

MULTIPLY 2 BY 5 GIVING RESULT
MULTIPLY NUMBER BY 10 GIVING PRODUCT
MULTIPLY 4 BY VARIABLE GIVING OUTPUT
MULTIPLY FACTOR1 BY FACTOR2 GIVING RESULTADO

DIVIDE 2 INTO 10 GIVING RESULT
DIVIDE NUMBER INTO 100 GIVING QUOTIENT
DIVIDE 5 INTO VALUE GIVING OUTPUT
DIVIDE NUM INTO DENOM GIVING RESULTADO

STOP RUN.